version: "3.8"
services:
  order:
    build:
      context: ./order
    mem_limit: 512m
    ports:
      - "8500-8502:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_USERNAME=logistapi
      - DB_PASSWORD=logistapi
      - DB_URL=postgres-order:5432
      - SERVER_PORT=8084
    env_file:
      - var.env
    depends_on:
      postgres-order:
        condition: service_healthy
      eureka:
        condition: service_started
    networks:
      - internal
    profiles:
      - prod
      - test
      - qa
  postgres-order:
    container_name: postgres-order
    image: postgres:13.3
    environment:
      POSTGRES_DB: "logist-api-order"
      POSTGRES_USER: "logistapi"
      POSTGRES_PASSWORD: "logistapi"
    ports:
      - "5436:5432"
    networks:
      - internal
    profiles:
      - prod
      - test
      - qa
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d logist-api-order -U logistapi"]
      interval: 10s
      timeout: 3s
      retries: 3
  product:
    build:
      context: ./product
    mem_limit: 512m
    ports:
      - "8200-8202:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_USERNAME=logistapi
      - DB_PASSWORD=logistapi
      - DB_URL=postgres-product:5432
      - SERVER_PORT=8081
    env_file:
      - var.env
    depends_on:
      postgres-product:
        condition: service_healthy
      eureka:
        condition: service_started
    networks:
      - internal
    profiles:
      - prod
      - test
      - qa
  postgres-product:
    container_name: postgres-product
    image: postgres:13.3
    environment:
      POSTGRES_DB: "logist-api-product"
      POSTGRES_USER: "logistapi"
      POSTGRES_PASSWORD: "logistapi"
    ports:
      - "5433:5432"
    networks:
      - internal
    profiles:
      - prod
      - qa
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d logist-api-product -U logistapi"]
      interval: 10s
      timeout: 3s
      retries: 3
  warehouse:
    build:
      context: ./warehouse
    mem_limit: 512m
    ports:
      - "8300-8302:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_USERNAME=logistapi
      - DB_PASSWORD=logistapi
      - DB_URL=postgres-warehouse:5432
      - SERVER_PORT=8082
    env_file:
      - var.env
    depends_on:
      postgres-warehouse:
        condition: service_healthy
      eureka:
        condition: service_started
    networks:
      - internal
    profiles:
      - prod
      - qa
  postgres-warehouse:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "logist-api-warehouse"
      POSTGRES_USER: "logistapi"
      POSTGRES_PASSWORD: "logistapi"
    ports:
      - "5434:5432"
    networks:
      - internal
    profiles:
      - prod
      - qa
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d logist-api-warehouse -U logistapi"]
      interval: 10s
      timeout: 3s
      retries: 3
  auth-server:
    build:
      context: ./auth-server
    mem_limit: 512m
    ports:
      - "8400-8402:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_USERNAME=logistapi
      - DB_PASSWORD=logistapi
      - DB_NAME=logist-api-users
      - DB_URL=postgres-users:5432
      - SERVER_PORT=8083
    env_file:
      - var.env
    depends_on:
      postgres-warehouse:
        condition: service_healthy
      eureka:
        condition: service_started
    networks:
      - internal
    profiles:
      - prod
      - test
      - qa
  postgres-users:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "logist-api-users"
      POSTGRES_USER: "logistapi"
      POSTGRES_PASSWORD: "logistapi"
    ports:
      - "5435:5432"
    networks:
      - internal
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d logist-api-users -U logistapi" ]
      interval: 10s
      timeout: 3s
      retries: 3
    profiles:
      - prod
      - test
      - qa
  eureka:
    build:
      context: ./eureka-server
    environment:
      - EUREKA_SERVER_HOST=eureka
      - EUREKA_SERVER_PORT=8761
    mem_limit: 512m
    ports:
      - "8761:8761"
    networks:
      - internal
    profiles:
      - prod
      - test
      - qa
  gateway:
    env_file:
      - var.env
    build:
      context: ./gateway
    mem_limit: 512m
    ports:
      - "8000:8080"
    depends_on:
      - eureka
      - order
      - warehouse
      - product
      - auth-server
    networks:
      - internal
    profiles:
      - prod
      - test
      - qa
networks:
  internal:


