version: "3.8"
services:
  order:
    build:
      context: ./order
    mem_limit: 512m
    ports:
      - "8100-8102:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_USERNAME=logistapi
      - DB_PASSWORD=logistapi
      - SERVER_PORT=8080
    env_file:
      - var.env
    depends_on:
      - mongo-order
      - eureka
    networks:
      - internal
  mongo-order:
    image: mongo:5.0.22
    ports:
      - '27020:27017'
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_DATABASE=logist-api-order
      - MONGO_INITDB_ROOT_USERNAME=logistapi
      - MONGO_INITDB_ROOT_PASSWORD=logistapi
    volumes:
      - ./order/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - internal
  product:
    build:
      context: ./product
    mem_limit: 512m
    ports:
      - "8200-8202:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_USERNAME=logistapi
      - DB_PASSWORD=logistapi
      - DB_URL=postgres-product:5432
      - UPLOAD_BASE_DIR=
      - SERVER_PORT=8081
    env_file:
      - var.env
    depends_on:
      postgres-product:
        condition: service_healthy
      eureka:
        condition: service_started
    networks:
      - internal
  postgres-product:
    container_name: postgres-product
    image: postgres:13.3
    environment:
      POSTGRES_DB: "logist-api-product"
      POSTGRES_USER: "logistapi"
      POSTGRES_PASSWORD: "logistapi"
    ports:
      - "5433:5432"
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d logist-api-product -U logistapi"]
      interval: 10s
      timeout: 3s
      retries: 3
  warehouse:
    build:
      context: ./warehouse
    mem_limit: 512m
    ports:
      - "8300-8302:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_USERNAME=logistapi
      - DB_PASSWORD=logistapi
      - DB_URL=postgres-warehouse:5432
      - SERVER_PORT=8082
    env_file:
      - var.env
    depends_on:
      postgres-warehouse:
        condition: service_healthy
      eureka:
        condition: service_started
    networks:
      - internal
  postgres-warehouse:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "logist-api-warehouse"
      POSTGRES_USER: "logistapi"
      POSTGRES_PASSWORD: "logistapi"
    ports:
      - "5434:5432"
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d logist-api-warehouse -U logistapi"]
      interval: 10s
      timeout: 3s
      retries: 3
  eureka:
    build:
      context: ./eureka-server
    mem_limit: 512m
    ports:
      - "8761:8761"
    networks:
      - internal
  gateway:
    env_file:
      - var.env
    build:
      context: ./gateway
    mem_limit: 512m
    ports:
      - "8000:8080"
    depends_on:
      - eureka
      - order
      - warehouse
      - product
    networks:
      - internal
networks:
  internal:


