spring:
  application:
    name: logistapi-auth
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_URL}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #   open when want to fetch new migrations data
    show-sql: false
  flyway:
    locations:
      - classpath:/db/migration

logging:
  charset:
    console: UTF-8
    file: UTF-8

springdoc:
  swagger-ui:
    path: /swagger-ui


bcrypt:
  encryption-rounds: 10

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}/eureka

logist-api:
  clock-zone-id: Europe/Moscow

master-user:
  email: ${MASTER_EMAIL}
  password: ${MASTER_PASSWORD}

jwt:
  access-token-expiration-minutes: 60
  refresh-token-expiration-days: 14
  access-token-secret: ${JWT_ACCESS_TOKEN_SECRET}
  refresh-token-secret: ${JWT_REFRESH_TOKEN_SECRET}