management:
  endpoint:
    health:
      enabled: true


spring:
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 8MB
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_URL}/logist-api-product
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #   open when want to fetch new migrations data
    show-sql: false

file-config:
  base-directory: C:\logist-api-product\
  max-image-size-mb: 8
  allowed-image-extensions-list: png,jpeg