spring:
  application:
    name: logistapi-product

springdoc:
  default-support-form-data: false
  swagger-ui:
    path: /swagger-ui

logist-api:
  clock-zone-id: Europe/Moscow

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}/eureka
