spring:
  application:
    name: logistapi-product
  flyway:
    locations:
      - classpath:/db/migration

springdoc:
  default-support-form-data: false
  swagger-ui:
    path: /swagger-ui

logging:
  charset:
    console: UTF-8
    file: UTF-8

logist-api:
  clock-zone-id: Europe/Moscow

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}/eureka

yandex:
  object-storage:
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    bucket-name: ${S3_BUCKET_NAME}
    aws-region: ${S3_AWS_REGION}
    endpoint: ${S3_ENDPOINT}

file-config:
  max-image-size-mb: 8
  allowed-image-extensions-list: png,jpeg

external-system:
  auth:
    service-name: logistapi-auth
    url: http://localhost:8080
    username: product@skladlain.ru
    password: skladlain-product