management:
  endpoint:
    health:
      enabled: true

spring:
  data:
    mongodb:
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      host: ${DB_HOST}
      port: ${DB_PORT}
      database: logist-api-order