spring:
  application:
    name: logistapi-order
  flyway:
    locations:
      - classpath:/db/migration

springdoc:
  default-support-form-data: false
  swagger-ui:
    path: /swagger-ui

logist-api:
  clock-zone-id: Europe/Moscow

logging:
  charset:
    console: UTF-8
    file: UTF-8

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}/eureka
