spring:
  application:
    name: logistapi-order

logging:
  charset:
    console: UTF-8
    file: UTF-8

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}/eureka