
service-names:
  product-service-name: ${PRODUCT_SERVICE_NAME}
  warehouse-service-name: ${WAREHOUSE_SERVICE_NAME}
  order-service-name: ${ORDER_SERVICE_NAME}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}/eureka

management:
  endpoint:
    health:
      show-details: "ALWAYS"
    web:
      exposure:
        include: "*"
    gateway:
      enabled: true


logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

spring:
  application:
    name: logistapi-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8081"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: swagger-ui
          uri: http://httpstat.us
          predicates:
            - Path=/swagger-ui**/**
          filters:
            - SetPath=/403
        - id: logistapi-product
          uri: lb://${PRODUCT_SERVICE_NAME}
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1
        - id: logistapi-order
          uri: lb://${ORDER_SERVICE_NAME}
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
        - id: logistapi-warehouse
          uri: lb://${WAREHOUSE_SERVICE_NAME}
          predicates:
            - Path=/warehouse/**
          filters:
            - StripPrefix=1
        - id: eureka-web-page
          uri: http://${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: eureka-other
          uri: http://${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}
          predicates:
            - Path=/eureka/**

