management:
  endpoint:
    health:
      enabled: true


spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_URL}/logist-api-warehouse
    driver-class-name: org.postgresql.Driver