spring:
  application:
    name: logistapi-warehouse

springdoc:
  swagger-ui:
    path: /swagger-ui

logist-api:
  clock-zone-id: Europe/Moscow
  initial-warehouse-code-counter: 1000000000

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}/eureka

product:
  url: ${PRODUCT_SERVICE_URL:localhost:}