spring:
  application:
    name: logistapi-warehouse
  flyway:
    locations:
      - classpath:/db/migration
  cloud:
    discovery:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui

logging:
  charset:
    console: UTF-8
    file: UTF-8

logist-api:
  clock-zone-id: Europe/Moscow
  initial-warehouse-code-counter: 1000000000

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}/eureka

external-system:
  product:
    service-name: ${PRODUCT_SERVICE_NAME}
    url: ${PRODUCT_SERVICE_URL}