server:
  port: 8761

spring:
  application:
    name: logistapi-discovery-service

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}/eureka